# https://docs.helix-editor.com/configuration.html

theme = "catppuccin_mocha"

[editor]
mouse = false
rulers = [80, 100]

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

# TIP: Bulk edit: % (select all) -> s (select by regex)

[keys.normal]
C-s = ":w"
"C-/" = "toggle_comments"
h = ":toggle lsp.display-inlay-hints"

[keys.normal.space]
W = [":toggle soft-wrap.enable", ":redraw"]
